// SPDX-License-Identifier: GPL-2.0-or-later

pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "forge-std/console.sol";

interface IEulerKinkyIRMFactory {
    function deploy(
        uint256 baseRate,
        uint256 slope,
        uint256 shape,
        uint32 kink,
        uint256 cutoff
    ) external returns (address);
}

/// @title Deploy Warren's Loop-Optimized Kinky IRM
/// @notice Deploys Kinky IRM with curve: 1% → 5.5% @ 80% → 100%
/// @dev Optimized for looping: liUSD collateral (earning 9.2%) can borrow at <5.5% up to 80% LTV
contract DeployLoopKinkyIRM is Script {
    
    // Mainnet EulerKinkyIRMFactory address
    address constant KINKY_IRM_FACTORY = 0x010102daAB6133d4f8cEB4C8842a70B9899Fc102;
    
    // Warren's Loop-Optimized Kinky IRM parameters
    // Generated by: node script/irm/kinky-irm-calculator.js 1 5.5 100 80
    struct KinkyParams {
        uint256 baseRate;  // 1% APY in SPY format
        uint256 slope;     // Slope for 0% → 80% linear section
        uint256 shape;     // Kinky curve steepness (70)
        uint32 kink;       // 80% utilization in uint32 scale
        uint256 cutoff;    // 100% APY max rate in SPY format
    }
    
    function getLoopOptimizedParams() internal pure returns (KinkyParams memory) {
        return KinkyParams({
            baseRate: 315522941107815300,        // 1% APY: low starting rate
            slope: 402285849,                    // Gradual slope: 1% → 5.5% over 80% utilization
            shape: 70,                           // Kinky steepness: aggressive post-80%
            kink: 3435973836,                    // 80% utilization: aligned with LTV
            cutoff: 21979553066486800000         // 100% APY: prevents excessive utilization
        });
    }
    
    function run() external returns (address kinkyIRM) {
        console.log("=== Deploying Warren Loop-Optimized Kinky IRM ===");
        console.log("");
        
        // Get calculated parameters
        KinkyParams memory params = getLoopOptimizedParams();
        
        console.log("Loop-Optimized Kinky IRM Parameters:");
        console.log("- Target Curve: 1%% -> 5.5%% @ 80%% -> 100%%");
        console.log("- Base Rate: ", params.baseRate, "(1%% APY)");
        console.log("- Slope: ", params.slope, "(gradual increase to kink)");
        console.log("- Shape: ", params.shape, "(kinky curve steepness)");
        console.log("- Kink: ", params.kink, "(80%% utilization)");
        console.log("- Cutoff: ", params.cutoff, "(100%% APY)");
        console.log("");
        
        // Start recording transactions
        vm.startBroadcast();
        
        // Deploy Kinky IRM via factory
        console.log("Deploying Loop-Optimized Kinky IRM...");
        kinkyIRM = IEulerKinkyIRMFactory(KINKY_IRM_FACTORY).deploy(
            params.baseRate,
            params.slope,
            params.shape,
            params.kink,
            params.cutoff
        );
        
        vm.stopBroadcast();
        
        console.log("=== Deployment Complete ===");
        console.log("Loop-Optimized Kinky IRM deployed at: ", kinkyIRM);
        console.log("");
        console.log("Features:");
        console.log("Looping enabled: Borrow cost (1-5.5%%) < liUSD yield (9.2%%)");
        console.log("LTV aligned: 80%% kink matches 80%% LTV for smooth experience");  
        console.log("Efficient capital: Low rates encourage productive leverage");
        console.log("Safety buffer: 20%% liquidity reserved at 80%% utilization");
        console.log("Emergency protection: Kinky curve post-80%% prevents over-leverage");
        console.log("");
        console.log("Next Steps:");
        console.log("1. Update WarrenCluster.s.sol with this IRM address");
        console.log("2. Deploy Warren vault cluster");
        console.log("3. Enable profitable looping strategies");
    }
}
